FROM centos:centos7

            ENV container docker
            RUN yum clean all
            RUN yum install -y sudo openssh-server openssh-clients which curl
            RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
            RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

          RUN if ! getent passwd kitchen; then                 useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen;               fi
          RUN echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          RUN echo "Defaults !requiretty" >> /etc/sudoers
          RUN mkdir -p /home/kitchen/.ssh
          RUN chown -R kitchen /home/kitchen/.ssh
          RUN chmod 0700 /home/kitchen/.ssh
          RUN touch /home/kitchen/.ssh/authorized_keys
          RUN chown kitchen /home/kitchen/.ssh/authorized_keys
          RUN chmod 0600 /home/kitchen/.ssh/authorized_keys


RUN echo ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQC8c157Z7d8vQFYDKCkQlX9cej8bBdDjhYNVr\+Sto/GdsHgRpGoMtuYApZM6IHnRpAR8PmLSdXxhF\+wtVCmFzuqwZvDyJGv6W66T45ow4vfAduhXwmLa1YwHWHCMAX9eS6pCjvbii92Y96ejw2qj57JbITL9a5Zgnq4YSrsuE13tgtbOLYmAm\+5/7NbTo4JrkYZsZpd7D61RyBhJcILd4YFprKFg2d9jh3\+BwNlC2Jh/QJ\+yHjgKIZmgcieCfQwy2ryF7XIsUMYRpOVUuiT\+Etn7lV6\+6LCWRgshH3R73\+6paOnNgz8i8po4YMGjHZBiLMc3hVOiJuuZ\+CQRxvY3D3X\ kitchen_docker_key >> /home/kitchen/.ssh/authorized_keys
